### ISSUE TITLE
generate_points() sometimes return an Empty Array 

### ISSUE THREAD

**Issue by daishishi** [udit/poisson-disc-sampling#1]
There is a bug where the `generate_points` function can return an empty array. This bug is more feasible / common with really low number of _retries_.
Apparently it can happen if the very first _spawn_points can't succeed finding a `_is_valid_sample()`, then the first and only element from _spawn_points is deleted. The _while loop_ is then exited and an empty array is return.

Personally I changed the if statement responsible for deleting elements from _spawn_points. With the code:
`if not sample_accepted and _points.size() > 0:`

I don't know much of Git so I didn't made a Merge Request, and instead opened a bug-issue.

**Comment by udit** [comment]
This is now fixed as per https://github.com/udit/poisson-disc-sampling/commit/c79c34cfaef909c593014e370dff5c6d1af54d47
