### ISSUE TITLE
Invalid set index in _generate_points()

### ISSUE THREAD

**Issue by stavguo** [udit/poisson-disc-sampling#3]
Hello, I've been using your add-on and it's been working great. However, this morning I got an error in poisson_disc_sampling.gd. On line 79 in _generate_points(), I got the following error: "Invalid set index '16' (on base: 'Array') with value of type 'int'". I've been using your add-on with Godot 4.1.3 stable. This is how I call your code:
```
var poisson_width: float = 2400
var poisson_height: float = 2400
var poisson_radius: int = 200
var poisson_retries: int = 30

var rect = Rect2(0,0,poisson_width,poisson_height)
delaunay = Delaunay.new(rect)
var corners = PackedVector2Array([
Vector2(0, poisson_height),
Vector2(0, 0),
Vector2(poisson_width, 0),
Vector2(poisson_width, poisson_height)
])
var points: Array = PoissonDiscSampling.generate_points_for_polygon(corners,
poisson_radius, poisson_retries)
```
Here are all the stack variables when the error occurred: 
![stack1](https://github.com/udit/poisson-disc-sampling/assets/55922644/3d92d71f-05c5-417c-a0a2-b17a971c2cfd)
![stack2](https://github.com/udit/poisson-disc-sampling/assets/55922644/8b5bd1ca-d673-4933-bacf-ea4d85e42459)
![stack3](https://github.com/udit/poisson-disc-sampling/assets/55922644/17f5b734-342a-48aa-bc87-dd1f5fa8ee35)
If there's any other information I can provide, please let me know. Thanks again for making this project.

**Comment by udit** [comment]
Thank you for posting stack variables!

Floating point precision error in `Geometry2D.is_point_in_polygon` function. I have fixed the bug and the update should be available from asset store once approved.
